# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-07 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='\u63a5\u53e3\u540d\u79f0')),
                ('httpType', models.CharField(choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTPS')], default='HTTP', max_length=50, verbose_name='http/https')),
                ('method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=50, verbose_name='\u8bf7\u6c42\u65b9\u5f0f')),
                ('apiAddress', models.CharField(max_length=1024, verbose_name='\u63a5\u53e3\u5730\u5740')),
                ('requestParameterType', models.CharField(choices=[('form-data', '\u8868\u5355(form-data)'), ('raw', '\u6e90\u6570\u636e(raw)')], default='1', max_length=50, verbose_name='\u8bf7\u6c42\u53c2\u6570\u683c\u5f0f')),
                ('status', models.CharField(default='', max_length=32, verbose_name='\u72b6\u60011\u6210\u529f\uff0c0\u5931\u8d25')),
                ('user', models.CharField(max_length=32, verbose_name='\u521b\u5efa\u4eba')),
                ('desc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='\u63cf\u8ff0')),
                ('CreateTime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('LastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='\u6700\u8fd1\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u63a5\u53e3',
                'verbose_name_plural': '\u63a5\u53e3\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='ApiHead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='\u6807\u7b7e')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='\u5185\u5bb9')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_web.ApiCase', verbose_name='\u6240\u5c5e\u63a5\u53e3')),
            ],
            options={
                'verbose_name': '\u8bf7\u6c42\u5934',
                'verbose_name_plural': '\u8bf7\u6c42\u5934\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='APIParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestParameterType', models.CharField(choices=[('form-data', '\u8868\u5355(form-data)'), ('raw', '\u6e90\u6570\u636e(raw)')], max_length=50, verbose_name='\u8bf7\u6c42\u53c2\u6570\u683c\u5f0f')),
                ('name', models.CharField(max_length=1024, verbose_name='\u53c2\u6570\u540d')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='\u5185\u5bb9')),
                ('paramType', models.CharField(choices=[('int', 'int'), ('string', 'string')], default='string', max_length=1024, verbose_name='\u7c7b\u578b')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameterList', to='django_web.ApiCase', verbose_name='\u63a5\u53e3')),
            ],
            options={
                'verbose_name': '\u63a5\u53e3\u53c2\u6570',
                'verbose_name_plural': '\u63a5\u53e3\u53c2\u6570\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='ApiParameterRaw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9')),
                ('api', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_web.ApiCase', verbose_name='\u6240\u5c5e\u63a5\u53e3')),
            ],
            options={
                'verbose_name': '\u8bf7\u6c42\u53c2\u6570Raw',
            },
        ),
        migrations.CreateModel(
            name='AutoApiCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='\u63a5\u53e3\u540d\u79f0')),
                ('httpType', models.CharField(choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTPS')], default='HTTPS', max_length=50, verbose_name='http/https')),
                ('method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=50, verbose_name='\u8bf7\u6c42\u65b9\u5f0f')),
                ('apiAddress', models.CharField(max_length=1024, verbose_name='\u63a5\u53e3\u5730\u5740')),
                ('requestParameterType', models.CharField(choices=[('form-data', '\u8868\u5355(form-data)'), ('raw', '\u6e90\u6570\u636e(raw)')], max_length=50, verbose_name='\u8bf7\u6c42\u53c2\u6570\u683c\u5f0f')),
                ('status', models.CharField(default='', max_length=32, verbose_name='\u8fd4\u56de\u7ed3\u679c')),
                ('sort', models.IntegerField(default=0, verbose_name='\u6392\u5e8f')),
                ('user', models.CharField(max_length=32, verbose_name='\u521b\u5efa\u4eba')),
                ('desc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='\u63cf\u8ff0')),
                ('CreateTime', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('LastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='\u6700\u8fd1\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6240\u5c5e\u63a5\u53e3',
                'verbose_name_plural': '\u6240\u5c5e\u63a5\u53e3\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='autoApiHead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='\u6807\u7b7e')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='\u5185\u5bb9')),
                ('autoApi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_web.AutoApiCase', verbose_name='\u6240\u5c5e\u63a5\u53e3')),
            ],
            options={
                'verbose_name': '\u7528\u4f8b\u8bf7\u6c42\u5934',
                'verbose_name_plural': '\u7528\u4f8b\u8bf7\u6c42\u5934\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='autoAPIParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestParameterType', models.CharField(choices=[('form-data', '\u8868\u5355(form-data)'), ('raw', '\u6e90\u6570\u636e(raw)')], max_length=50, verbose_name='\u8bf7\u6c42\u53c2\u6570\u683c\u5f0f')),
                ('name', models.CharField(max_length=1024, verbose_name='\u53c2\u6570\u540d')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='\u5185\u5bb9')),
                ('paramType', models.CharField(choices=[('int', 'int'), ('string', 'string')], default='string', max_length=1024, verbose_name='\u7c7b\u578b')),
                ('autoApi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameterList', to='django_web.AutoApiCase', verbose_name='\u63a5\u53e3')),
            ],
            options={
                'verbose_name': '\u7528\u4f8b\u63a5\u53e3\u53c2\u6570',
                'verbose_name_plural': '\u7528\u4f8b\u63a5\u53e3\u53c2\u6570\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='autoApiParameterRaw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9')),
                ('autoApi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_web.AutoApiCase', verbose_name='\u6240\u5c5e\u63a5\u53e3')),
            ],
            options={
                'verbose_name': '\u8bf7\u6c42\u53c2\u6570Raw',
            },
        ),
        migrations.CreateModel(
            name='AutoTaskRunTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.CharField(max_length=50, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('endTime', models.CharField(max_length=50, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('testTime', models.CharField(default='', max_length=50, verbose_name='\u6d4b\u8bd5\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u4f8b\u4efb\u52a1\u6267\u884c\u65f6\u95f4',
                'verbose_name_plural': '\u7528\u4f8b\u4efb\u52a1\u6267\u884c\u65f6\u95f4',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='\u7528\u4f8b\u540d\u79f0')),
                ('user', models.CharField(max_length=32, verbose_name='\u521b\u5efa\u4eba')),
                ('desc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='\u63cf\u8ff0')),
                ('status', models.CharField(default='4', max_length=32, verbose_name='\u72b6\u6001\uff1a1\u6210\u529f\uff0c2\u5931\u8d25 3\u672a\u5b8c\u6210 4\u672a\u5f00\u59cb')),
                ('CreateTime', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('LastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='\u6700\u8fd1\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u4f8b',
                'verbose_name_plural': '\u7528\u4f8b\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('env_name', models.CharField(max_length=32)),
                ('env_url', models.CharField(max_length=100, verbose_name='\u8bbf\u95ee\u5730\u5740')),
                ('evn_port', models.CharField(max_length=10, verbose_name='\u7aef\u53e3')),
                ('env_desc', models.CharField(default='', max_length=1000)),
                ('env_createTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('user', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('version', models.CharField(max_length=50, verbose_name='\u7248\u672c')),
                ('type', models.CharField(choices=[('Web', 'Web'), ('App', 'App')], max_length=50, verbose_name='\u7c7b\u578b')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='\u63cf\u8ff0')),
                ('status', models.BooleanField(default=True, verbose_name='\u72b6\u6001')),
                ('LastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='\u6700\u8fd1\u4fee\u6539\u65f6\u95f4')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('user', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='step',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='\u6b65\u9aa4\u540d\u79f0')),
                ('type', models.CharField(max_length=20, verbose_name='\u6b65\u9aa4\u7c7b\u578b')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='\u6b65\u9aa4\u6392\u5e8f')),
                ('content', models.CharField(max_length=200, verbose_name='\u6b65\u9aa4\u7c7b\u578b')),
                ('autoCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_web.AutoApiCase', verbose_name='\u6240\u5c5e\u9879\u76ee')),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='\u4efb\u52a1\u540d')),
                ('desc', models.CharField(max_length=1024, verbose_name='\u4efb\u52a1\u63cf\u8ff0')),
                ('type', models.CharField(choices=[('circulation', '\u5faa\u73af'), ('timing', '\u5b9a\u65f6')], default='timing', max_length=50, verbose_name='\u7c7b\u578b')),
                ('time', models.CharField(max_length=1024, verbose_name='\u5b9a\u65f6')),
                ('status', models.IntegerField(default=0, verbose_name='1:\u6267\u884c\u4e2d\uff0c2\uff1a\u7ed3\u675f\uff0c0\uff1a\u5f85\u6267\u884c,3:\u6682\u505c')),
                ('startTime', models.DateTimeField(verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('endTime', models.DateTimeField(verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('user', models.CharField(default='', max_length=32, verbose_name='\u521b\u5efa\u4eba')),
                ('env_id', models.CharField(default='', max_length=32, verbose_name='\u73af\u5883')),
                ('CreateTime', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('min', models.CharField(default='*', max_length=32, verbose_name='\u5206\u949f')),
                ('hour', models.CharField(default='*', max_length=32, verbose_name='\u5c0f\u65f6')),
                ('day', models.CharField(default='*', max_length=32, verbose_name='\u5929')),
                ('month', models.CharField(default='*', max_length=32, verbose_name='\u6708')),
                ('week', models.CharField(default='*', max_length=32, verbose_name='\u5468')),
            ],
        ),
        migrations.CreateModel(
            name='taskCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField(default=0, verbose_name='\u4efb\u52a1')),
                ('case_id', models.IntegerField(default=0, verbose_name='\u7528\u4f8b')),
            ],
        ),
        migrations.CreateModel(
            name='taskResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_id', models.IntegerField(default=0, verbose_name='\u7528\u4f8b')),
                ('autoApi_id', models.IntegerField(default=0, verbose_name='\u7528\u4f8b')),
                ('result', models.CharField(choices=[('PASS', '\u6210\u529f'), ('FAIL', '\u5931\u8d25'), ('ERROR', '\u5f02\u5e38')], max_length=50, verbose_name='\u6d4b\u8bd5\u7ed3\u679c')),
                ('httpStatus', models.CharField(blank=True, choices=[('200', '200'), ('404', '404'), ('400', '400'), ('502', '502'), ('500', '500'), ('302', '302')], max_length=50, null=True, verbose_name='http\u72b6\u6001')),
                ('responseData', models.TextField(blank=True, null=True, verbose_name='\u5b9e\u9645\u8fd4\u56de\u5185\u5bb9')),
                ('user', models.CharField(max_length=32, verbose_name='\u521b\u5efa\u4eba')),
                ('testTime', models.CharField(default='', max_length=50, verbose_name='\u6d4b\u8bd5\u65f6\u95f4')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_web.task', verbose_name='\u4efb\u52a1\u5173\u8054')),
            ],
            options={
                'verbose_name': '\u6d4b\u8bd5\u7ed3\u679c',
                'verbose_name_plural': '\u6d4b\u8bd5\u7ed3\u679c\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statusCode', models.CharField(blank=True, choices=[('200', '200'), ('404', '404'), ('400', '400'), ('502', '502'), ('500', '500'), ('302', '302')], max_length=1024, null=True, verbose_name='\u671f\u671bHTTP\u72b6\u6001')),
                ('examineType', models.CharField(max_length=1024, verbose_name='\u5339\u914d\u89c4\u5219')),
                ('data', models.TextField(blank=True, null=True, verbose_name='\u89c4\u5219\u5185\u5bb9')),
                ('result', models.CharField(choices=[('PASS', '\u6210\u529f'), ('FAIL', '\u5931\u8d25'), ('ERROR', '\u5f02\u5e38')], max_length=50, verbose_name='\u6d4b\u8bd5\u7ed3\u679c')),
                ('httpStatus', models.CharField(blank=True, choices=[('200', '200'), ('404', '404'), ('400', '400'), ('502', '502'), ('500', '500'), ('302', '302')], max_length=50, null=True, verbose_name='http\u72b6\u6001')),
                ('responseData', models.TextField(blank=True, null=True, verbose_name='\u5b9e\u9645\u8fd4\u56de\u5185\u5bb9')),
                ('user', models.CharField(max_length=32, verbose_name='\u521b\u5efa\u4eba')),
                ('autoApi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_web.AutoApiCase', verbose_name='\u63a5\u53e3')),
            ],
            options={
                'verbose_name': '\u6d4b\u8bd5\u7ed3\u679c',
                'verbose_name_plural': '\u6d4b\u8bd5\u7ed3\u679c\u7ba1\u7406',
            },
        ),
        migrations.AddField(
            model_name='env',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_web.Project'),
        ),
        migrations.AddField(
            model_name='case',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_web.Project', verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='autotaskruntime',
            name='task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='django_web.task', verbose_name='\u4efb\u52a1'),
        ),
        migrations.AddField(
            model_name='autoapicase',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_web.Case', verbose_name='\u6240\u5c5e\u7528\u4f8b'),
        ),
        migrations.AddField(
            model_name='autoapicase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_web.Project', verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='apicase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_web.Project', verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
    ]
