# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-19 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_id', models.IntegerField(default=0, verbose_name='\u7528\u4f8b')),
                ('autoApi_id', models.IntegerField(default=0, verbose_name='\u7528\u4f8b')),
                ('result', models.CharField(choices=[('PASS', '\u6210\u529f'), ('FAIL', '\u5931\u8d25')], max_length=50, verbose_name='\u6d4b\u8bd5\u7ed3\u679c')),
                ('httpStatus', models.CharField(blank=True, choices=[('200', '200'), ('404', '404'), ('400', '400'), ('502', '502'), ('500', '500'), ('302', '302')], max_length=50, null=True, verbose_name='http\u72b6\u6001')),
                ('responseData', models.TextField(blank=True, null=True, verbose_name='\u5b9e\u9645\u8fd4\u56de\u5185\u5bb9')),
                ('user', models.CharField(max_length=32, verbose_name='\u521b\u5efa\u4eba')),
            ],
            options={
                'verbose_name': '\u6d4b\u8bd5\u7ed3\u679c',
                'verbose_name_plural': '\u6d4b\u8bd5\u7ed3\u679c\u7ba1\u7406',
            },
        ),
        migrations.RenameField(
            model_name='autotaskruntime',
            old_name='elapsedTime',
            new_name='endTime',
        ),
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.CharField(default='*', max_length=32, verbose_name='\u5929'),
        ),
        migrations.AlterField(
            model_name='task',
            name='hour',
            field=models.CharField(default='*', max_length=32, verbose_name='\u5c0f\u65f6'),
        ),
        migrations.AlterField(
            model_name='task',
            name='min',
            field=models.CharField(default='*', max_length=32, verbose_name='\u5206\u949f'),
        ),
        migrations.AlterField(
            model_name='task',
            name='month',
            field=models.CharField(default='*', max_length=32, verbose_name='\u6708'),
        ),
        migrations.AlterField(
            model_name='task',
            name='week',
            field=models.CharField(default='*', max_length=32, verbose_name='\u5468'),
        ),
        migrations.AddField(
            model_name='taskresult',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_web.task', verbose_name='\u4efb\u52a1\u5173\u8054'),
        ),
    ]
