# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-21 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0002_auto_20190119_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autotaskruntime',
            name='project',
        ),
        migrations.AddField(
            model_name='autotaskruntime',
            name='task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='django_web.task', verbose_name='\u9879\u76ee'),
        ),
    ]
