# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-22 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0003_auto_20190121_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotaskruntime',
            name='task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='django_web.task', verbose_name='\u4efb\u52a1'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='', max_length=50, verbose_name='1:\u6267\u884c\u4e2d\uff0c2\uff1a\u7ed3\u675f\uff0c0\uff1a\u5f85\u6267\u884c'),
        ),
    ]
