# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-22 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0004_auto_20190122_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(default=0, verbose_name='1:\u6267\u884c\u4e2d\uff0c2\uff1a\u7ed3\u675f\uff0c0\uff1a\u5f85\u6267\u884c'),
        ),
    ]
